### PR TITLE
Simplified display of queue position to ordinal numbers

### PR DESCRIPTION
**Pull request by maw101**
This PR simplifies the display of a student's position in the queue by changing from whole numbers (i.e. 0, 1, 2, ...) to ordinal numbers (i.e. 1, 2, 3, ...).

This changes the display of a queue position from:
- "position 0" to "position 1"
- "position 1" to "position 2"
- etc.

### CODE REVIEW

**Comment by IdrisTheDragon** [comment]
As the bot is designed to be used in the computer science department I don't see the problem with the queue starting at 0 instead of 1...

**Review by IdrisTheDragon — APPROVED** [review]

**Comment by maw101** [comment]
Oops sorry, didn't meant to re-request a review

**Comment by Amheus** [comment]
heyah
I have no issue with the queue starting at 1 instead of 0 if need be
however, this is a minor UX update and since the userbase is practically all compscis anyways, it might not make that much of a difference
*especially* since users have already had a year of the queue starting at 0

\- cerys

**Review by Amheus — COMMENTED** [review]
I rewrote a large bulk of the code you've requested updates for but looks good
@JoelLucaAdams would be in a better position than myself to comment on whether this would need updating in other locations

**Comment by JoelLucaAdams** [comment]
Yeah, I'm happy with the design changes made here. I think we originally left the queue to start at 0 as it felt like more of a funny inside joke about arrays, however it does make sense to add this feature to reduce confusion.

**Review by JoelLucaAdams — APPROVED** [review]

**Comment by Amheus** [comment]
Good morning @maw101,
Unfortuantly due to merge conflicts with https://github.com/AberDiscordBotsTeam/demoHelperBot/pull/42, I'm reverting this commit.
The modifications you made will be added into the new codebase this afternoon.

Best,
Cerys

**Pull request merged**
